[package]
name = "putil"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
tokio-postgres = { version = "0.7.13", features = ["with-uuid-1"] }
uuid = "1.17.0"
